// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package database

import (
	"time"
)

type AdminUser struct {
	ID           int32
	FirstName    string
	LastName     string
	BodyWeight   string
	Username     string
	Email        string
	Password     string
	Lastloggedin time.Time
}
