// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package database

import (
	"database/sql"
)

type AdminUser struct {
	ID           int32
	FirstName    sql.NullString
	LastName     sql.NullString
	BodyWeight   sql.NullString
	Username     sql.NullString
	Email        sql.NullString
	Password     sql.NullString
	Lastloggedin sql.NullTime
}
