-- +goose Up
CREATE TABLE workouts (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  start_time TIMESTAMP NOT NULL,
  duration DECIMAL NOT NULL,
  total_weight DECIMAL NOT NULL,
  total_calories INT NOT NULL,
  user_id INT NOT NULL
);

ALTER TABLE workouts ADD FOREIGN KEY ("user_id") REFERENCES "Admin"."Users" ("id") ON DELETE CASCADE;

-- +goose Down
DROP TABLE workouts;
