-- +goose Up
CREATE TYPE intensity AS ENUM (
  'Low',
  'Medium',
  'High',
  'Very High'
);

CREATE TABLE sets (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exercise TEXT NOT NULL,
  count INT NOT NULL,
  intensity intensity NOT NULL,
  "type" TEXT NOT NULL,
  weight DECIMAL NOT NULL,
  workout_id INT NOT NULL
);

ALTER TABLE "sets" ADD FOREIGN KEY ("workout_id") REFERENCES workouts ("id") ON DELETE CASCADE;

-- +goose Down
DROP TABLE "sets";

DROP TYPE intensity;
