-- +goose Up
CREATE TYPE intensity AS ENUM (
  'Low',
  'Medium',
  'High',
  'Very High'
);

CREATE TABLE sets (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exercise TEXT NOT NULL,
  count INT NOT NULL,
  intensity intensity NOT NULL,
  "type" TEXT NOT NULL,
  workout_id INT NOT NULL
);

CREATE TABLE reps (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  weight DECIMAL NOT NULL,
  set_id INT NOT NULL
);

ALTER TABLE "sets" ADD FOREIGN KEY ("workout_id") REFERENCES workouts ("id") ON DELETE CASCADE;

ALTER TABLE "reps" ADD FOREIGN KEY ("set_id") REFERENCES reps ("id") ON DELETE CASCADE;

-- +goose Down
DROP TABLE "reps";

DROP TABLE "sets";

DROP TYPE intensity;
