-- +goose Up
CREATE TYPE crud AS ENUM (
  'CREATE',
  'READ',
  'UPDATE',
  'DELETE'
);

CREATE TABLE roles (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL
);

INSERT INTO roles (id, name) VALUES (0, 'User');
INSERT INTO roles (id, name) VALUES (1, 'Admin');

CREATE TABLE permissions (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resource text NOT NULL,
  action crud NOT NULL
);

CREATE TABLE rolesPermissions (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_id INT REFERENCES roles ("id") ON DELETE CASCADE,
  permission_id INT REFERENCES permissions ("id") ON DELETE CASCADE
);

ALTER TABLE "Admin"."Users" 
ADD role_id INT NOT NULL DEFAULT 0 
REFERENCES roles ("id") ON DELETE CASCADE;

-- +goose Down
ALTER TABLE "Admin"."Users" 
DROP COLUMN role_id;

DROP TABLE rolesPermissions;

DROP TABLE permissions;

DROP TABLE roles;

DROP TYPE intensity;